# Generated by Django 5.2.6 on 2025-09-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_exceldata_data_exceldata_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
