# Generated by Django 5.2.6 on 2025-09-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='data',
        ),
        migrations.AddField(
            model_name='exceldata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
